Dump compilation failure summary while generating report (#491)
Add a summary list of iree compilation failure based on actual error. 

Summary dumped in the file <report_file>_compilation_erros.md and looks
like :

# COMPILATION ERROR ANALYSIS

**Total compilation failures: 6**

| Status | Count |
|---|---|
| Timeouts | 2 |
| Errors | 4 |
| No log | 0 |

## ERRORS (grouped by error)

| Error | Count |
|---|---|
| 'OP' op failed to distribute | 2 |
| function 'OP' uses 77824 bytes of shared memory | 1 |
| 'OP' op inferred input/output operand #2 has shape's dimension #1 to
be 769, but found 768 | 1 |

## ERROR TESTS (grouped by error)

### Error: 'OP' op failed to distribute

**Count: 2**

| test_name | command | error |
|---|---|---|
| cait_m36_384 | iree-compile
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cait_m36_384/model.torch_onnx.mlir
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cait_m36_384/compiled_model.vmfb
| 'func.func' op failed to distribute |
| cait_m36_384_Opset16 | iree-compile
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cait_m36_384_Opset16/model.torch_onnx.mlir
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cait_m36_384_Opset16/compiled_model.vmfb
| 'func.func' op failed to distribute |

### Error: function 'OP' uses 77824 bytes of shared memory

**Count: 1**

| test_name | command | error |
|---|---|---|
| eca_nfnet_l0_Opset16 | iree-compile
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/eca_nfnet_l0_Opset16/model.torch_onnx.mlir
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/eca_nfnet_l0_Opset16/compiled_model.vmfb
| function 'main_graph$async_dispatch_15_conv_2x64x28x28x64x3x3_f32'
uses 77824 bytes of shared memory |

### Error: 'OP' op inferred input/output operand #2 has shape's
dimension #1 to be 769, but found 768

**Count: 1**

| test_name | command | error |
|---|---|---|
| funnel_Opset16 | iree-compile
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/funnel_Opset16/model.torch_onnx.mlir
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/funnel_Opset16/compiled_model.vmfb
| 'linalg.generic' op inferred input/output operand #2 has shape's
dimension #1 to be 769, but found 768 |

## TIMEOUT TESTS

| test_name | command |
|---|---|
| cs3darknet_focus_m_train_vaiq | iree-compile
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cs3darknet_focus_m_train_vaiq/model.torch_onnx.mlir
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cs3darknet_focus_m_train_vaiq/compiled_model.vmfb
|
| cs3darknet_focus_m_vaiq | iree-compile
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cs3darknet_focus_m_vaiq/model.torch_onnx.mlir
--iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o
/home/prosenj/work/AMD-SHARK-TestSuite/alt_e2eamdshark/FailedRun/.././failed-run/cs3darknet_focus_m_vaiq/compiled_model.vmfb
|


This is done by adding info into the report json, hence should work with
merge_dicts and other report generation framework. \


TODO : As of now, this code is specific to handling compilation error.
Later we should generalize such reports for all stage errors